version: "3"

services:
  projects:
    build: ./website
    container_name: projects
    ports:
      - 5000:5000
    environment:
      VIRTUAL_HOST: ids-projects.137.120.31.102.nip.io
      LETSENCRYPT_HOST: ids-projects.137.120.31.102.nip.io
